import oracledb
import os

def main():
    print("Connecting to Oracle ADB...")
    oracle_conn = oracledb.connect(
        user=os.environ.get("DB_USER", "ADMIN"),
        password=os.environ.get("DB_PASSWORD"),
        dsn=os.environ.get("DB_DSN"),
        wallet_location="C:\\Users\\mayur\\.gemini\\antigravity\\scratch\\lms-new\\wallet",
        wallet_password=os.environ.get("DB_PASSWORD")
    )
    cursor = oracle_conn.cursor()

    stmts = [
        "ALTER TABLE chapters ADD (content_path_clob CLOB)",
        "UPDATE chapters SET content_path_clob = content_path",
        "ALTER TABLE chapters DROP COLUMN content_path",
        "ALTER TABLE chapters RENAME COLUMN content_path_clob TO content_path",
        
        "DROP TABLE daily_booster_attempts",
        "CREATE TABLE daily_booster_attempts (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id NUMBER, \"DATE\" TIMESTAMP, score NUMBER, xp_earned NUMBER, created_at TIMESTAMP)"
    ]

    for stmt in stmts:
        try:
            cursor.execute(stmt)
            print(f"Executed: {stmt}")
        except Exception as e:
            print(f"Error: {e}")

    oracle_conn.commit()
    print("Done!")

if __name__ == "__main__":
    main()
