import mysql.connector
import oracledb
import os
import re

def map_mysql_to_oracle_type(mysql_type):
    mysql_type = mysql_type.lower()
    if 'int' in mysql_type or 'tinyint' in mysql_type or 'boolean' in mysql_type:
        return 'NUMBER'
    elif 'varchar' in mysql_type or 'char' in mysql_type or 'text' in mysql_type or 'json' in mysql_type:
        return 'VARCHAR2(4000)'
    elif 'datetime' in mysql_type or 'timestamp' in mysql_type or 'date' in mysql_type:
        return 'TIMESTAMP'
    elif 'decimal' in mysql_type or 'float' in mysql_type or 'double' in mysql_type:
        return 'NUMBER'
    else:
        return 'VARCHAR2(4000)'

def main():
    print("Connecting to MySQL...")
    mysql_conn = mysql.connector.connect(
        host="127.0.0.1",
        port=3307,
        user="root",
        password="",
        database="lms"
    )
    mysql_cursor = mysql_conn.cursor(dictionary=True)
    
    print("Connecting to Oracle ADB...")
    oracle_conn = oracledb.connect(
        user=os.environ.get("DB_USER", "ADMIN"),
        password=os.environ.get("DB_PASSWORD"),
        dsn=os.environ.get("DB_DSN"),
        wallet_location="/home/ubuntu/wallet",
        wallet_password=os.environ.get("DB_PASSWORD")
    )
    oracle_cursor = oracle_conn.cursor()

    mysql_cursor.execute("SHOW TABLES")
    tables = [list(row.values())[0] for row in mysql_cursor.fetchall()]
    
    for table in tables:
        print(f"Processing table: {table}")
        mysql_cursor.execute(f"DESCRIBE {table}")
        columns = mysql_cursor.fetchall()
        
        col_defs = []
        primary_keys = []
        for col in columns:
            col_name = col['Field'].upper()
            oracle_type = map_mysql_to_oracle_type(col['Type'])
            
            # Special handling for auto increment PK
            if 'auto_increment' in str(col['Extra']).lower():
                col_defs.append(f"{col_name} {oracle_type} GENERATED BY DEFAULT AS IDENTITY")
            else:
                col_defs.append(f"{col_name} {oracle_type}")
                
            if col['Key'] == 'PRI':
                primary_keys.append(col_name)
        
        pk_constraint = ""
        if primary_keys:
            pk_constraint = f", CONSTRAINT PK_{table.upper()[:25]} PRIMARY KEY ({', '.join(primary_keys)})"
            
        create_stmt = f"CREATE TABLE {table.upper()} (\n  {',\n  '.join(col_defs)}{pk_constraint}\n)"
        
        try:
            oracle_cursor.execute(create_stmt)
            print(f"  -> Created successfully.")
        except Exception as e:
            if "ORA-00955" in str(e):
                print(f"  -> Table already exists.")
            else:
                print(f"  -> ERROR: {e}\n{create_stmt}")

    oracle_conn.commit()
    print("Done!")

if __name__ == "__main__":
    main()
