import 'package:flutter/material.dart';
import '../services/api_service.dart';
import '../widgets/app_sidebar.dart';

class AppConfigScreen extends StatefulWidget{const AppConfigScreen({super.key});@override State<AppConfigScreen> createState()=>_AppConfigScreenState();}
class _AppConfigScreenState extends State<AppConfigScreen>{final api=ApiService(),latest=TextEditingController(),minimum=TextEditingController(),url=TextEditingController();bool loading=true,saving=false;String? error;
  @override void initState(){super.initState();load();}@override void dispose(){latest.dispose();minimum.dispose();url.dispose();super.dispose();}
  Future<void> load()async{try{final value=await api.getAppConfig();latest.text=value['latest_android_version']?.toString()??'1.0.0';minimum.text=value['min_android_version']?.toString()??'1.0.0';url.text=value['apk_download_url']?.toString()??'';error=null;}catch(e){error=e.toString();}if(mounted)setState(()=>loading=false);}
  Future<void> save()async{if(latest.text.trim().isEmpty||minimum.text.trim().isEmpty)return;setState(()=>saving=true);try{await api.saveAppConfig({'latest_android_version':latest.text.trim(),'min_android_version':minimum.text.trim(),'apk_download_url':url.text.trim().isEmpty?null:url.text.trim()});if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Mobile application configuration saved.')));}catch(e){error=e.toString();}if(mounted)setState(()=>saving=false);}
  @override Widget build(BuildContext context)=>Scaffold(drawer:const AppSidebar(role:'admin'),appBar:AppBar(title:const Text('Mobile Application Configuration')),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(24),children:[if(error!=null)Text(error!,style:const TextStyle(color:Colors.red)),const Text('Control which Android application release participants should use. Version values should use the format 1.2.3.'),const SizedBox(height:20),TextField(controller:latest,decoration:const InputDecoration(labelText:'Latest Android version',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:minimum,decoration:const InputDecoration(labelText:'Minimum supported Android version',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:url,keyboardType:TextInputType.url,decoration:const InputDecoration(labelText:'APK download URL (optional)',border:OutlineInputBorder())),const SizedBox(height:20),Align(alignment:Alignment.centerRight,child:FilledButton.icon(onPressed:saving?null:save,icon:const Icon(Icons.save),label:Text(saving?'Saving…':'Save configuration')))]));
}
