import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../services/api_service.dart';
import '../widgets/app_sidebar.dart';

class ParticipantContentScreen extends StatefulWidget{const ParticipantContentScreen({super.key});@override State<ParticipantContentScreen> createState()=>_ParticipantContentScreenState();}
class _ParticipantContentScreenState extends State<ParticipantContentScreen> with SingleTickerProviderStateMixin{final api=ApiService(),search=TextEditingController();late TabController tabs;bool loadingPages=true,searching=false;String? error;List<Map<String,dynamic>> pages=[],results=[];
  @override void initState(){super.initState();tabs=TabController(length:2,vsync:this);loadPages();}@override void dispose(){tabs.dispose();search.dispose();super.dispose();}
  Future<void> loadPages()async{try{pages=await api.getPublicPages();error=null;}catch(e){error=e.toString();}if(mounted)setState(()=>loadingPages=false);}
  Future<void> runSearch()async{final value=search.text.trim();if(value.length<2){setState(()=>results=[]);return;}setState(()=>searching=true);try{results=await api.searchParticipantContent(value);error=null;}catch(e){error=e.toString();}if(mounted)setState(()=>searching=false);}
  String plain(dynamic value)=>value?.toString().replaceAll(RegExp(r'<[^>]*>'), ' ').replaceAll(RegExp(r'\s+'),' ').trim()??'';
  Future<void> openPage(Map<String,dynamic> item)async{try{final page=await api.getPublicPage(item['slug'].toString());if(!mounted)return;await showDialog<void>(context:context,builder:(dialogContext)=>AlertDialog(title:Text(page['title'].toString()),content:SizedBox(width:720,child:SingleChildScrollView(child:SelectableText(plain(page['content'])))),actions:[TextButton(onPressed:()=>Navigator.pop(dialogContext),child:const Text('Close'))]));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Could not load page: $e')));}}
  @override Widget build(BuildContext context)=>Scaffold(drawer:const AppSidebar(role:'participant'),appBar:AppBar(title:const Text('Search & Information'),bottom:TabBar(controller:tabs,tabs:const[Tab(icon:Icon(Icons.search),text:'Search'),Tab(icon:Icon(Icons.article),text:'Information')])),body:TabBarView(controller:tabs,children:[Column(children:[Padding(padding:const EdgeInsets.all(16),child:TextField(controller:search,onSubmitted:(_)=>runSearch(),decoration:InputDecoration(labelText:'Search assigned courses and quizzes',prefixIcon:const Icon(Icons.search),suffixIcon:IconButton(onPressed:runSearch,icon:const Icon(Icons.arrow_forward)),border:const OutlineInputBorder()))),if(searching)const LinearProgressIndicator(),if(error!=null)Padding(padding:const EdgeInsets.all(12),child:Text(error!,style:const TextStyle(color:Colors.red))),Expanded(child:results.isEmpty?Center(child:Text(search.text.trim().length<2?'Enter at least two characters.':'Nothing found. Try different keywords.')):ListView.builder(itemCount:results.length,itemBuilder:(_,index){final item=results[index],course=item['type']=='course';return Card(child:ListTile(leading:CircleAvatar(child:Icon(course?Icons.menu_book:Icons.quiz)),title:Text(item['title'].toString()),subtitle:Text(plain(item['description']),maxLines:2,overflow:TextOverflow.ellipsis),trailing:course?const Icon(Icons.arrow_forward):const Chip(label:Text('Quiz')),onTap:course?()=>context.go('/participant/courses/${item['id']}'):null));}))]),loadingPages?const Center(child:CircularProgressIndicator()):pages.isEmpty?const Center(child:Text('No information pages are currently published.')):ListView.builder(padding:const EdgeInsets.all(16),itemCount:pages.length,itemBuilder:(_,index){final page=pages[index];return Card(child:ListTile(leading:const Icon(Icons.article_outlined),title:Text(page['title'].toString()),subtitle:Text(plain(page['content']),maxLines:2,overflow:TextOverflow.ellipsis),trailing:const Icon(Icons.chevron_right),onTap:()=>openPage(page)));})]));
}
