import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../services/api_service.dart';
import '../widgets/app_sidebar.dart';

class ParticipantAiToolsScreen extends StatefulWidget{const ParticipantAiToolsScreen({super.key});@override State<ParticipantAiToolsScreen> createState()=>_ParticipantAiToolsScreenState();}
class _ParticipantAiToolsScreenState extends State<ParticipantAiToolsScreen>{final api=ApiService();final chapter=TextEditingController(),attempt=TextEditingController(),question=TextEditingController();bool busy=false;String? error;dynamic output;
  @override void dispose(){chapter.dispose();attempt.dispose();question.dispose();super.dispose();}
  Future<void> run(Future<dynamic> Function() action)async{setState((){busy=true;error=null;});try{output=await action();}catch(e){error=e.toString();}if(mounted)setState(()=>busy=false);}
  int? number(TextEditingController c)=>int.tryParse(c.text.trim());
  @override Widget build(BuildContext context)=>Scaffold(drawer:const AppSidebar(role:'participant'),appBar:AppBar(title:const Text('My AI Learning Assistant')),body:ListView(padding:const EdgeInsets.all(20),children:[if(error!=null)Card(color:Colors.red.shade50,child:Padding(padding:const EdgeInsets.all(12),child:Text(error!,style:const TextStyle(color:Colors.red)))),Card(child:ListTile(leading:const Icon(Icons.auto_awesome),title:const Text('Recommended next learning'),subtitle:const Text('Uses your assigned-course progress to suggest what to continue.'),trailing:FilledButton(onPressed:busy?null:()=>run(api.getAiRecommendations),child:const Text('Recommend')))),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:chapter,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Chapter ID',helperText:'Shown in the chapter URL',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:question,maxLength:500,maxLines:3,decoration:const InputDecoration(labelText:'Ask about this chapter',border:OutlineInputBorder())),Wrap(spacing:8,children:[FilledButton(onPressed:busy||number(chapter)==null||question.text.trim().isEmpty?null:()=>run(()=>api.askAi(number(chapter)!,question.text.trim())),child:const Text('Ask')),OutlinedButton(onPressed:busy||number(chapter)==null?null:()=>run(()=>api.getAiTakeaways(number(chapter)!)),child:const Text('Key takeaways'))])]))),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:attempt,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Completed quiz attempt ID',border:OutlineInputBorder())),const SizedBox(height:10),FilledButton.tonal(onPressed:busy||number(attempt)==null?null:()=>run(()=>api.getAiHints(number(attempt)!)),child:const Text('Explain incorrect answers'))]))),if(busy)const LinearProgressIndicator(),if(output!=null)Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('AI response',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:10),SelectableText(output is String?output.toString():const JsonEncoder.withIndent('  ').convert(output)),if(output is Map&&output['courses'] is List)...List<Map<String,dynamic>>.from(output['courses']).map((c)=>ListTile(title:Text(c['title'].toString()),subtitle:Text('${c['progress']}% complete'),trailing:const Icon(Icons.arrow_forward),onTap:()=>context.go('/participant/courses/${c['id']}')))]))) ]));
}
