import 'package:flutter/material.dart';
import 'dart:typed_data';
import 'package:file_picker/file_picker.dart';
import 'package:provider/provider.dart';
import '../providers/auth_provider.dart';
import '../services/api_service.dart';
import '../widgets/app_sidebar.dart';

class ReportsScreen extends StatefulWidget{const ReportsScreen({super.key});@override State<ReportsScreen> createState()=>_State();}
class _State extends State<ReportsScreen> with SingleTickerProviderStateMixin{final api=ApiService();late TabController tabs;bool loading=true;String? error;DateTime from=DateTime.now().subtract(const Duration(days:30)),to=DateTime.now();List<String> stores=[],cities=[],managers=[];List<Map<String,dynamic>> courses=[],courseRows=[],quizRows=[],roleplayRows=[],userRows=[];Map<String,dynamic> summary={};String? store,city,manager;int? courseId;
@override void initState(){super.initState();tabs=TabController(length:4,vsync:this);loadOptions();}@override void dispose(){tabs.dispose();super.dispose();}
Future<void> loadOptions()async{try{final o=await api.getReportOptions();stores=List<String>.from(o['stores']??const[]);cities=List<String>.from(o['cities']??const[]);managers=List<String>.from(o['managers']??const[]);courses=List<Map<String,dynamic>>.from(o['courses']??const[]);await load();}catch(e){if(mounted)setState((){error=e.toString();loading=false;});}}
Future<void> load()async{setState(()=>loading=true);try{final d=await api.getReports(from:from,to:to,store:store,city:city,manager:manager,courseId:courseId);summary=Map<String,dynamic>.from(d['summary']??{});courseRows=List<Map<String,dynamic>>.from(d['courses']??const[]);quizRows=List<Map<String,dynamic>>.from(d['quizzes']??const[]);roleplayRows=List<Map<String,dynamic>>.from(d['roleplays']??const[]);userRows=List<Map<String,dynamic>>.from(d['users']??const[]);error=null;}catch(e){error=e.toString();}if(mounted)setState(()=>loading=false);}
Future<void> pick(bool start)async{final value=await showDatePicker(context:context,initialDate:start?from:to,firstDate:DateTime(2020),lastDate:DateTime.now());if(value!=null)setState(()=>start?from=value:to=value);}
Future<void> exportCsv()async{final type=const['courses','quizzes','roleplays','users'][tabs.index];try{final bytes=await api.exportReportCsv(type:type,from:from,to:to,store:store,city:city,manager:manager,courseId:courseId);await FilePicker.platform.saveFile(dialogTitle:'Save report CSV',fileName:'${type}_${from.toIso8601String().substring(0,10)}_${to.toIso8601String().substring(0,10)}.csv',type:FileType.custom,allowedExtensions:const['csv'],bytes:Uint8List.fromList(bytes));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Export failed: $e')));}}
Widget filters()=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Wrap(spacing:10,runSpacing:10,crossAxisAlignment:WrapCrossAlignment.center,children:[OutlinedButton.icon(onPressed:()=>pick(true),icon:const Icon(Icons.calendar_today),label:Text('From ${from.toIso8601String().substring(0,10)}')),OutlinedButton.icon(onPressed:()=>pick(false),icon:const Icon(Icons.calendar_today),label:Text('To ${to.toIso8601String().substring(0,10)}')),SizedBox(width:170,child:DropdownButtonFormField<String>(initialValue:store,decoration:const InputDecoration(labelText:'Store'),items:[const DropdownMenuItem(value:null,child:Text('All')), ...stores.map((v)=>DropdownMenuItem(value:v,child:Text(v)))],onChanged:(v)=>setState(()=>store=v))),SizedBox(width:170,child:DropdownButtonFormField<String>(initialValue:city,decoration:const InputDecoration(labelText:'City'),items:[const DropdownMenuItem(value:null,child:Text('All')), ...cities.map((v)=>DropdownMenuItem(value:v,child:Text(v)))],onChanged:(v)=>setState(()=>city=v))),SizedBox(width:210,child:DropdownButtonFormField<String>(initialValue:manager,decoration:const InputDecoration(labelText:'Manager'),items:[const DropdownMenuItem(value:null,child:Text('All')), ...managers.map((v)=>DropdownMenuItem(value:v,child:Text(v)))],onChanged:(v)=>setState(()=>manager=v))),SizedBox(width:210,child:DropdownButtonFormField<int>(initialValue:courseId,decoration:const InputDecoration(labelText:'Course'),items:[const DropdownMenuItem(value:null,child:Text('All')), ...courses.map((v)=>DropdownMenuItem(value:v['id'] as int,child:Text(v['title'].toString(),overflow:TextOverflow.ellipsis)))],onChanged:(v)=>setState(()=>courseId=v))),FilledButton.icon(onPressed:load,icon:const Icon(Icons.filter_alt),label:const Text('Apply'))])));
Widget metrics()=>Wrap(spacing:12,runSpacing:12,children:summary.entries.map((e)=>SizedBox(width:190,child:Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(e.key.replaceAll('_',' ').toUpperCase(),style:const TextStyle(fontSize:11,color:Colors.grey)),Text('${e.value}',style:const TextStyle(fontSize:28,fontWeight:FontWeight.bold))]))))).toList());
Widget courseList()=>ListView.builder(itemCount:courseRows.length,itemBuilder:(c,i){final r=courseRows[i];return Card(child:ListTile(title:Text(r['course_title']?.toString()??''),subtitle:Text('${r['full_name']} • ${r['store_code']??''}\n${r['completed_chapters']}/${r['total_chapters']} chapters • ${r['last_activity']??'No activity'}'),isThreeLine:true,trailing:Chip(label:Text('${r['progress_percent']}%'))));});
Widget quizList()=>ListView.builder(itemCount:quizRows.length,itemBuilder:(c,i){final r=quizRows[i];return Card(child:ListTile(title:Text(r['quiz_title']?.toString()??''),subtitle:Text('${r['full_name']} • ${r['store_code']??''}\n${r['end_time']??'Not attempted'}'),isThreeLine:true,trailing:Chip(label:Text(r['percentage']==null?'Pending':'${r['percentage']}%'))));});
Widget roleplayList()=>ListView.builder(itemCount:roleplayRows.length,itemBuilder:(c,i){final r=roleplayRows[i];return Card(child:ListTile(title:Text(r['scenario_topic']?.toString()??''),subtitle:Text('${r['full_name']} • ${r['week_no']}/${r['day']}\n${r['status']}'),isThreeLine:true,trailing:r['observer_score']==null?null:Chip(label:Text('${r['observer_score']}/5'))));});
Widget userList()=>ListView.builder(itemCount:userRows.length,itemBuilder:(c,i){final r=userRows[i];return Card(child:ListTile(title:Text(r['full_name']?.toString()??''),subtitle:Text('${r['store_code']??''} • ${r['city']??''}\nLast login: ${r['last_login']??'Never'}'),isThreeLine:true,trailing:Chip(label:Text('${r['login_count']} logins'))));});
@override Widget build(BuildContext context){final role=context.watch<AuthProvider>().role??'trainer';return Scaffold(drawer:AppSidebar(role:role),appBar:AppBar(title:Text(role=='area_manager'?'Team Reports':'Reports'),actions:[IconButton(tooltip:'Export selected tab',onPressed:loading?null:exportCsv,icon:const Icon(Icons.download))],bottom:TabBar(controller:tabs,isScrollable:true,tabs:const[Tab(text:'Courses'),Tab(text:'Quizzes'),Tab(text:'Roleplays'),Tab(text:'Users')])),body:Column(children:[Padding(padding:const EdgeInsets.all(12),child:filters()),if(!loading&&error==null)Padding(padding:const EdgeInsets.symmetric(horizontal:12),child:metrics()),const SizedBox(height:8),Expanded(child:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Text('Could not load reports: $error')):TabBarView(controller:tabs,children:[courseList(),quizList(),roleplayList(),userList()]))]));}}
