import 'package:flutter/material.dart';
import '../services/api_service.dart';
import '../widgets/lms_shell.dart';

class TrainerNotificationsScreen extends StatefulWidget{const TrainerNotificationsScreen({super.key});@override State<TrainerNotificationsScreen> createState()=>_State();}
class _State extends State<TrainerNotificationsScreen>{final api=ApiService();bool loading=true,sending=false;String? error;List<Map<String,dynamic>> participants=[],history=[];List<String> stores=[],managers=[];final selected=<int>{};String mode='all',type='system';final title=TextEditingController(),message=TextEditingController(),image=TextEditingController(),schedule=TextEditingController();String? store,manager;
@override void initState(){super.initState();load();}@override void dispose(){title.dispose();message.dispose();image.dispose();schedule.dispose();super.dispose();}
Future<void> load()async{setState(()=>loading=true);try{final r=await Future.wait([api.getNotificationOptions(),api.getSentNotifications()]);final o=r[0] as Map<String,dynamic>;participants=List<Map<String,dynamic>>.from(o['participants']??const[]);stores=List<String>.from(o['store_codes']??const[]);managers=List<String>.from(o['manager_names']??const[]);history=r[1] as List<Map<String,dynamic>>;error=null;}catch(e){error=e.toString();}if(mounted)setState(()=>loading=false);}
Future<void> send()async{if(title.text.trim().isEmpty||message.text.trim().isEmpty)return;setState(()=>sending=true);try{final result=await api.sendNotification({'title':title.text.trim(),'message':message.text.trim(),'type':type,'image_path':image.text.trim().isEmpty?null:image.text.trim(),'scheduled_at':schedule.text.trim().isEmpty?null:DateTime.parse(schedule.text.trim()).toIso8601String(),'all_participants':mode=='all','user_ids':mode=='individual'?selected.toList():[],'store_codes':mode=='store'&&store!=null?[store]:[],'manager_names':mode=='manager'&&manager!=null?[manager]:[]});title.clear();message.clear();image.clear();schedule.clear();selected.clear();if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('${result['scheduled']==true?'Scheduled':'Sent'} to ${result['recipients']} participants.')));await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}if(mounted)setState(()=>sending=false);}
Widget targets()=>Column(children:[SegmentedButton<String>(segments:const[ButtonSegment(value:'all',label:Text('All')),ButtonSegment(value:'individual',label:Text('People')),ButtonSegment(value:'store',label:Text('Store')),ButtonSegment(value:'manager',label:Text('Manager'))],selected:{mode},onSelectionChanged:(v)=>setState(()=>mode=v.first)),if(mode=='store')DropdownButtonFormField<String>(initialValue:store,items:stores.map((v)=>DropdownMenuItem(value:v,child:Text(v))).toList(),onChanged:(v)=>setState(()=>store=v),decoration:const InputDecoration(labelText:'Store')),if(mode=='manager')DropdownButtonFormField<String>(initialValue:manager,items:managers.map((v)=>DropdownMenuItem(value:v,child:Text(v))).toList(),onChanged:(v)=>setState(()=>manager=v),decoration:const InputDecoration(labelText:'Reporting manager')),if(mode=='individual')Container(constraints:const BoxConstraints(maxHeight:220),child:ListView(children:participants.map((p){final id=p['id'] as int;return CheckboxListTile(dense:true,value:selected.contains(id),title:Text(p['full_name']?.toString()??p['username'].toString()),subtitle:Text(p['store_code']?.toString()??''),onChanged:(v)=>setState(()=>v==true?selected.add(id):selected.remove(id)));}).toList()))]);
@override Widget build(BuildContext context)=>LmsShell(title:'Notifications',rootPage:true,actions:[IconButton(tooltip:'Refresh notifications',onPressed:load,icon:const Icon(Icons.refresh))],body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Text('Notification history is temporarily unavailable.')):ListView(padding:const EdgeInsets.all(20),children:[Text('Send or schedule notification',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:12),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:title,decoration:const InputDecoration(labelText:'Title')),TextField(controller:message,maxLines:4,decoration:const InputDecoration(labelText:'Message')),DropdownButtonFormField<String>(initialValue:type,items:const[DropdownMenuItem(value:'system',child:Text('System')),DropdownMenuItem(value:'nudge',child:Text('Nudge')),DropdownMenuItem(value:'badge_earned',child:Text('Congratulations')),DropdownMenuItem(value:'at_risk',child:Text('Urgent warning'))],onChanged:(v)=>setState(()=>type=v!),decoration:const InputDecoration(labelText:'Style')),TextField(controller:image,decoration:const InputDecoration(labelText:'Image URL (optional)')),TextField(controller:schedule,decoration:const InputDecoration(labelText:'Schedule time with timezone',hintText:'2026-07-25T09:00:00+05:30')),const SizedBox(height:12),targets(),const SizedBox(height:12),Align(alignment:Alignment.centerRight,child:FilledButton.icon(onPressed:sending?null:send,icon:const Icon(Icons.send),label:Text(sending?'Sending…':'Send notification')))]))),const SizedBox(height:24),Text('Recent broadcasts',style:Theme.of(context).textTheme.headlineSmall),...history.map((h)=>Card(child:ListTile(title:Text(h['title']?.toString()??''),subtitle:Text('${h['message']??''}\n${h['scheduled_at']??h['created_at']??''}'),isThreeLine:true,trailing:Chip(label:Text('${h['read_count']??0}/${h['recipients_count']??0} read')))))]));}
