import 'package:flutter/material.dart';
import '../services/api_service.dart';
import '../widgets/lms_shell.dart';

class TrainerGamificationScreen extends StatefulWidget {const TrainerGamificationScreen({super.key});@override State<TrainerGamificationScreen> createState()=>_State();}
class _State extends State<TrainerGamificationScreen> with SingleTickerProviderStateMixin{
 final api=ApiService();late TabController tabs;bool loading=true;String? error;List<Map<String,dynamic>> badges=[],rewards=[],redemptions=[],settings=[];
 @override void initState(){super.initState();tabs=TabController(length:4,vsync:this);load();}@override void dispose(){tabs.dispose();super.dispose();}
 Future<void> load()async{setState(()=>loading=true);try{final d=await api.getTrainerGamification();badges=List<Map<String,dynamic>>.from(d['badges']??const[]);rewards=List<Map<String,dynamic>>.from(d['rewards']??const[]);redemptions=List<Map<String,dynamic>>.from(d['redemptions']??const[]);settings=List<Map<String,dynamic>>.from(d['settings']??const[]);error=null;}catch(e){error=e.toString();}if(mounted)setState(()=>loading=false);}
 Future<void> badgeDialog([Map<String,dynamic>? item])async{final name=TextEditingController(text:item?['name']?.toString()),desc=TextEditingController(text:item?['description']?.toString()),icon=TextEditingController(text:item?['icon_path']?.toString()??'🏅'),trigger=TextEditingController(text:item?['badge_trigger']?.toString());final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:Text(item==null?'Create badge':'Edit badge'),content:SizedBox(width:480,child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Name')),TextField(controller:desc,decoration:const InputDecoration(labelText:'Description')),TextField(controller:icon,decoration:const InputDecoration(labelText:'Emoji, SVG, or image URL')),TextField(controller:trigger,decoration:const InputDecoration(labelText:'Automatic trigger (optional)'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()async{if(name.text.trim().isEmpty)return;await api.saveBadge({'name':name.text.trim(),'description':desc.text.trim(),'icon_path':icon.text.trim(),'badge_trigger':trigger.text.trim().isEmpty?null:trigger.text.trim()},item?['id'] as int?);if(c.mounted)Navigator.pop(c,true);},child:const Text('Save'))]));if(ok==true)load();}
 Future<void> rewardDialog()async{final title=TextEditingController(),desc=TextEditingController(),cost=TextEditingController(),stock=TextEditingController(text:'-1');final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Create reward'),content:SizedBox(width:480,child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:title,decoration:const InputDecoration(labelText:'Title')),TextField(controller:desc,decoration:const InputDecoration(labelText:'Description')),TextField(controller:cost,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'XP cost')),TextField(controller:stock,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Stock (-1 unlimited)'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()async{final xp=int.tryParse(cost.text),qty=int.tryParse(stock.text);if(title.text.trim().isEmpty||xp==null||qty==null)return;await api.createReward({'title':title.text.trim(),'description':desc.text.trim(),'xp_cost':xp,'stock':qty,'image_url':null});if(c.mounted)Navigator.pop(c,true);},child:const Text('Create'))]));if(ok==true)load();}
 Widget badgeList()=>ListView(padding:const EdgeInsets.all(20),children:[Align(alignment:Alignment.centerRight,child:FilledButton.icon(onPressed:()=>badgeDialog(),icon:const Icon(Icons.add),label:const Text('Create badge'))),...badges.map((b)=>Card(child:ListTile(leading:Text(b['icon_path']?.toString()??'🏅',style:const TextStyle(fontSize:28)),title:Text(b['name']?.toString()??''),subtitle:Text('${b['description']??''}\nAwarded ${b['awarded_count']??0} times'),isThreeLine:true,onTap:()=>badgeDialog(b),trailing:IconButton(onPressed:()async{await api.deleteBadge(b['id'] as int);load();},icon:const Icon(Icons.delete_outline)))))]);
 Widget rewardList()=>ListView(padding:const EdgeInsets.all(20),children:[Align(alignment:Alignment.centerRight,child:FilledButton.icon(onPressed:rewardDialog,icon:const Icon(Icons.add),label:const Text('Create reward'))),...rewards.map((r)=>Card(child:ListTile(title:Text(r['title']?.toString()??''),subtitle:Text('${r['xp_cost']} XP • stock ${r['stock']==-1?'unlimited':r['stock']}'),trailing:IconButton(onPressed:()async{await api.deleteReward(r['id'] as int);load();},icon:const Icon(Icons.delete_outline)))))]);
 Widget redemptionList()=>redemptions.isEmpty?const Center(child:Text('No redemptions.')):ListView(padding:const EdgeInsets.all(20),children:redemptions.map((r)=>Card(child:ListTile(title:Text('${r['full_name']} — ${r['reward_title']}'),subtitle:Text('${r['store_code']??''} • ${r['redeemed_at']??''}'),trailing:PopupMenuButton<String>(initialValue:r['status']?.toString(),onSelected:(v)async{await api.updateRedemption(r['id'] as int,v);load();},itemBuilder:(_)=>const[PopupMenuItem(value:'Approved',child:Text('Approve')),PopupMenuItem(value:'Rejected',child:Text('Reject & refund')),PopupMenuItem(value:'Fulfilled',child:Text('Mark fulfilled'))])))).toList());
 Widget pointsList(){final controls={for(final s in settings)s['key'].toString():TextEditingController(text:s['value']?.toString())};return ListView(padding:const EdgeInsets.all(20),children:[...settings.map((s)=>TextField(controller:controls[s['key']],decoration:InputDecoration(labelText:s['key'].toString().replaceAll('_',' '),helperText:s['description']?.toString()))),const SizedBox(height:20),Align(alignment:Alignment.centerRight,child:FilledButton(onPressed:()async{await api.updatePointsSettings(controls.map((k,v)=>MapEntry(k,v.text.trim())));load();},child:const Text('Save points settings')))]);}
 @override Widget build(BuildContext context)=>LmsShell(title:'Gamification',rootPage:true,appBarBottom:TabBar(controller:tabs,isScrollable:true,tabs:const[Tab(text:'Badges'),Tab(text:'Rewards'),Tab(text:'Redemptions'),Tab(text:'Points')]),actions:[IconButton(tooltip:'Refresh gamification',onPressed:load,icon:const Icon(Icons.refresh))],body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Text('Gamification data is temporarily unavailable.')):TabBarView(controller:tabs,children:[badgeList(),rewardList(),redemptionList(),pointsList()]));
}
